// <auto-generated />
using BurstPool.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BurstPool.Migrations
{
    [DbContext(typeof(PoolContext))]
    [Migration("20180119214305_AddedRewardTracking")]
    partial class AddedRewardTracking
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BurstPool.Database.Models.Account", b =>
                {
                    b.Property<ulong>("Id");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BurstPool.Database.Models.AccountBalance", b =>
                {
                    b.Property<ulong>("AccountId");

                    b.Property<decimal>("PendingBalance");

                    b.HasKey("AccountId");

                    b.ToTable("AccountBalances");
                });

            modelBuilder.Entity("BurstPool.Database.Models.AccountTransaction", b =>
                {
                    b.Property<string>("Id");

                    b.Property<ulong?>("AccountBalanceAccountId");

                    b.Property<ulong>("AccountId");

                    b.Property<decimal>("Adjustment");

                    b.Property<long>("BlockId");

                    b.HasKey("Id");

                    b.HasIndex("AccountBalanceAccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BlockId");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("BurstPool.Database.Models.Block", b =>
                {
                    b.Property<long>("Height");

                    b.Property<ulong>("BaseTarget");

                    b.Property<decimal>("Difficulty");

                    b.HasKey("Height");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("BurstPool.Database.Models.BlockState", b =>
                {
                    b.Property<long>("Height");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<bool>("IsPoolMember");

                    b.Property<string>("PoolTransactionId");

                    b.Property<ulong>("Winner");

                    b.HasKey("Height");

                    b.HasIndex("Created");

                    b.HasIndex("PoolTransactionId");

                    b.ToTable("BlockStates");
                });

            modelBuilder.Entity("BurstPool.Database.Models.Earnings", b =>
                {
                    b.Property<long>("Height");

                    b.Property<decimal>("Amount");

                    b.HasKey("Height");

                    b.ToTable("Earnings");
                });

            modelBuilder.Entity("BurstPool.Database.Models.PoolTransaction", b =>
                {
                    b.Property<string>("Id");

                    b.Property<decimal>("Adjustment");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<long>("Height");

                    b.Property<decimal>("PoolBalance");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Height");

                    b.ToTable("PoolTransactions");
                });

            modelBuilder.Entity("BurstPool.Database.Models.Share", b =>
                {
                    b.Property<string>("Id");

                    b.Property<ulong>("AccountId");

                    b.Property<long>("BlockId");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<ulong>("Deadline");

                    b.Property<ulong>("Nonce");

                    b.Property<decimal>("ShareValue");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BlockId");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("BurstPool.Database.Models.AccountBalance", b =>
                {
                    b.HasOne("BurstPool.Database.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BurstPool.Database.Models.AccountTransaction", b =>
                {
                    b.HasOne("BurstPool.Database.Models.AccountBalance")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountBalanceAccountId");

                    b.HasOne("BurstPool.Database.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BurstPool.Database.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BurstPool.Database.Models.BlockState", b =>
                {
                    b.HasOne("BurstPool.Database.Models.Block", "Block")
                        .WithOne("BlockState")
                        .HasForeignKey("BurstPool.Database.Models.BlockState", "Height")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BurstPool.Database.Models.PoolTransaction", "PoolTransaction")
                        .WithMany()
                        .HasForeignKey("PoolTransactionId");
                });

            modelBuilder.Entity("BurstPool.Database.Models.PoolTransaction", b =>
                {
                    b.HasOne("BurstPool.Database.Models.Block", "Block")
                        .WithMany("PoolTransactions")
                        .HasForeignKey("Height")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BurstPool.Database.Models.Share", b =>
                {
                    b.HasOne("BurstPool.Database.Models.Account", "Account")
                        .WithMany("Shares")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BurstPool.Database.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
